use itertools::Itertools;
use malachite_base::bools::exhaustive::exhaustive_bools;
use malachite_base::chars::exhaustive::exhaustive_ascii_chars;
use malachite_base::nevers::nevers;
use malachite_base::num::exhaustive::exhaustive_unsigneds;
use malachite_base::tuples::exhaustive::exhaustive_units;
use malachite_base::vecs::exhaustive::exhaustive_vecs;
use std::fmt::Debug;

fn exhaustive_vecs_helper<I: Clone + Iterator>(xs: I, out: &[&[I::Item]])
where
    I::Item: Clone + Debug + Eq,
{
    let xss = exhaustive_vecs(xs).take(20).collect_vec();
    assert_eq!(xss.iter().map(Vec::as_slice).collect_vec().as_slice(), out);
}

#[test]
fn test_exhaustive_vecs() {
    exhaustive_vecs_helper(nevers(), &[&[]]);
    exhaustive_vecs_helper(
        exhaustive_units(),
        &[
            &[],
            &[()],
            &[(), ()],
            &[(), (), (), ()],
            &[(), (), ()],
            &[(), (), (), (), ()],
            &[(), (), (), (), (), ()],
            &[(), (), (), (), (), (), (), (), ()],
            &[(), (), (), (), (), (), ()],
            &[(), (), (), (), (), (), (), ()],
            &[(), (), (), (), (), (), (), (), (), ()],
            &[(), (), (), (), (), (), (), (), (), (), (), ()],
            &[(), (), (), (), (), (), (), (), (), (), ()],
            &[(), (), (), (), (), (), (), (), (), (), (), (), ()],
            &[(), (), (), (), (), (), (), (), (), (), (), (), (), ()],
            &[
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
            ],
            &[(), (), (), (), (), (), (), (), (), (), (), (), (), (), ()],
            &[
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
            ],
            &[
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
            ],
            &[
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
                (),
            ],
        ],
    );
    exhaustive_vecs_helper(
        exhaustive_bools(),
        &[
            &[],
            &[false],
            &[true],
            &[false, false, false],
            &[false, false],
            &[false, false, true],
            &[false, true],
            &[false, false, false, false, false],
            &[true, false],
            &[false, true, false],
            &[true, true],
            &[false, false, false, false],
            &[false, true, true],
            &[false, false, false, true],
            &[true, false, false],
            &[false, false, false, false, false, false, false],
            &[true, false, true],
            &[false, false, true, false],
            &[true, true, false],
            &[false, false, false, false, true],
        ],
    );
    exhaustive_vecs_helper(
        'a'..='c',
        &[
            &[],
            &['a'],
            &['b'],
            &['a', 'a', 'a'],
            &['c'],
            &['a', 'a'],
            &['a', 'b'],
            &['a', 'a', 'a', 'a', 'a'],
            &['b', 'a'],
            &['a', 'a', 'b'],
            &['b', 'b'],
            &['a', 'a', 'a', 'a'],
            &['a', 'c'],
            &['a', 'b', 'a'],
            &['b', 'c'],
            &['a', 'a', 'a', 'a', 'a', 'a'],
            &['c', 'a'],
            &['a', 'b', 'b'],
            &['c', 'b'],
            &['a', 'a', 'a', 'b'],
        ],
    );
    exhaustive_vecs_helper(
        exhaustive_ascii_chars(),
        &[
            &[],
            &['a'],
            &['b'],
            &['a', 'a', 'a'],
            &['c'],
            &['a', 'a'],
            &['d'],
            &['a', 'a', 'a', 'a'],
            &['e'],
            &['a', 'b'],
            &['f'],
            &['a', 'a', 'b'],
            &['g'],
            &['b', 'a'],
            &['h'],
            &['a', 'a', 'a', 'a', 'a'],
            &['i'],
            &['b', 'b'],
            &['j'],
            &['a', 'b', 'a'],
        ],
    );
    exhaustive_vecs_helper(
        exhaustive_unsigneds::<u32>(),
        &[
            &[],
            &[0],
            &[1],
            &[0, 0, 0],
            &[2],
            &[0, 0],
            &[3],
            &[0, 0, 0, 0],
            &[4],
            &[0, 1],
            &[5],
            &[0, 0, 1],
            &[6],
            &[1, 0],
            &[7],
            &[0, 0, 0, 0, 0],
            &[8],
            &[1, 1],
            &[9],
            &[0, 1, 0],
        ],
    );
}
