use malachite_test::common::DemoBenchRegistry;

pub mod log_base_2;
pub mod mod_add;
pub mod mod_mul;
pub mod mod_op;
pub mod mod_pow;
pub mod mod_power_of_2;
pub mod mod_power_of_2_add;
pub mod mod_power_of_2_mul;
pub mod mod_power_of_2_pow;
pub mod mod_power_of_2_shl;
pub mod mod_power_of_2_shr;
pub mod mod_power_of_2_square;
pub mod mod_power_of_2_sub;
pub mod mod_shl;
pub mod mod_shr;
pub mod mod_square;
pub mod mod_sub;
pub mod neg;
pub mod next_power_of_2;
pub mod overflowing_abs;
pub mod overflowing_add;
pub mod overflowing_add_mul;
pub mod overflowing_div;
pub mod overflowing_mul;
pub mod overflowing_neg;
pub mod overflowing_pow;
pub mod overflowing_square;
pub mod overflowing_sub;
pub mod overflowing_sub_mul;
pub mod parity;
pub mod pow;
pub mod power_of_2;
pub mod round_to_multiple;
pub mod round_to_multiple_of_power_of_2;
pub mod saturating_abs;
pub mod saturating_add;
pub mod saturating_add_mul;
pub mod saturating_mul;
pub mod saturating_neg;
pub mod saturating_pow;
pub mod saturating_square;
pub mod saturating_sub;
pub mod saturating_sub_mul;
pub mod shl_round;
pub mod shr_round;
pub mod sign;
pub mod square;
pub mod wrapping_abs;
pub mod wrapping_add;
pub mod wrapping_add_mul;
pub mod wrapping_div;
pub mod wrapping_mul;
pub mod wrapping_neg;
pub mod wrapping_pow;
pub mod wrapping_square;
pub mod wrapping_sub;
pub mod wrapping_sub_mul;
pub mod xx_add_yy_is_zz;
pub mod xx_div_mod_y_is_qr;
pub mod xx_sub_yy_is_zz;
pub mod xxx_add_yyy_is_zzz;
pub mod xxx_sub_yyy_is_zzz;
pub mod xxxx_add_yyyy_is_zzzz;

pub(crate) fn register(registry: &mut DemoBenchRegistry) {
    log_base_2::register(registry);
    mod_add::register(registry);
    mod_mul::register(registry);
    mod_op::register(registry);
    mod_pow::register(registry);
    mod_power_of_2::register(registry);
    mod_power_of_2_add::register(registry);
    mod_power_of_2_mul::register(registry);
    mod_power_of_2_pow::register(registry);
    mod_power_of_2_shl::register(registry);
    mod_power_of_2_shr::register(registry);
    mod_power_of_2_square::register(registry);
    mod_power_of_2_sub::register(registry);
    mod_shl::register(registry);
    mod_shr::register(registry);
    mod_square::register(registry);
    mod_sub::register(registry);
    neg::register(registry);
    next_power_of_2::register(registry);
    overflowing_abs::register(registry);
    overflowing_add::register(registry);
    overflowing_add_mul::register(registry);
    overflowing_div::register(registry);
    overflowing_mul::register(registry);
    overflowing_neg::register(registry);
    overflowing_pow::register(registry);
    overflowing_square::register(registry);
    overflowing_sub::register(registry);
    overflowing_sub_mul::register(registry);
    parity::register(registry);
    pow::register(registry);
    power_of_2::register(registry);
    round_to_multiple::register(registry);
    round_to_multiple_of_power_of_2::register(registry);
    saturating_abs::register(registry);
    saturating_add::register(registry);
    saturating_add_mul::register(registry);
    saturating_mul::register(registry);
    saturating_neg::register(registry);
    saturating_pow::register(registry);
    saturating_square::register(registry);
    saturating_sub::register(registry);
    saturating_sub_mul::register(registry);
    shl_round::register(registry);
    shr_round::register(registry);
    sign::register(registry);
    square::register(registry);
    wrapping_abs::register(registry);
    wrapping_add::register(registry);
    wrapping_add_mul::register(registry);
    wrapping_div::register(registry);
    wrapping_mul::register(registry);
    wrapping_neg::register(registry);
    wrapping_pow::register(registry);
    wrapping_square::register(registry);
    wrapping_sub::register(registry);
    wrapping_sub_mul::register(registry);
    xx_add_yy_is_zz::register(registry);
    xx_div_mod_y_is_qr::register(registry);
    xx_sub_yy_is_zz::register(registry);
    xxx_add_yyy_is_zzz::register(registry);
    xxx_sub_yyy_is_zzz::register(registry);
    xxxx_add_yyyy_is_zzzz::register(registry);
}
