use malachite_test::common::DemoBenchRegistry;

pub mod mod_power_of_2_pow;
pub mod mod_power_of_2_shl;
pub mod mod_power_of_2_shr;
pub mod mod_power_of_2_square;
pub mod mod_power_of_2_sub;
pub mod mod_shl;
pub mod mod_shr;
pub mod mod_square;
pub mod mod_sub;
pub mod next_power_of_2;
pub mod parity;
pub mod pow;
pub mod power_of_2;
pub mod round_to_multiple;
pub mod round_to_multiple_of_power_of_2;
pub mod saturating_sub;
pub mod saturating_sub_mul;
pub mod shl;
pub mod shl_round;
pub mod shr;
pub mod shr_round;
pub mod sign;
pub mod square;
pub mod sub;
pub mod sub_mul;

pub(crate) fn register(registry: &mut DemoBenchRegistry) {
    mod_power_of_2_pow::register(registry);
    mod_power_of_2_shl::register(registry);
    mod_power_of_2_shr::register(registry);
    mod_power_of_2_square::register(registry);
    mod_power_of_2_sub::register(registry);
    mod_shl::register(registry);
    mod_shr::register(registry);
    mod_square::register(registry);
    mod_sub::register(registry);
    next_power_of_2::register(registry);
    parity::register(registry);
    pow::register(registry);
    power_of_2::register(registry);
    round_to_multiple::register(registry);
    round_to_multiple_of_power_of_2::register(registry);
    saturating_sub::register(registry);
    saturating_sub_mul::register(registry);
    shl::register(registry);
    shl_round::register(registry);
    shr::register(registry);
    shr_round::register(registry);
    sign::register(registry);
    square::register(registry);
    sub::register(registry);
    sub_mul::register(registry);
}
